name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - 'feature/**'  # Optional: track feature branches

env:
  IMAGE_NAME: todo-ui
  ACR_NAME: acrdevtodoapp01
  ACR_LOGIN_SERVER: acrdevtodoapp01.azurecr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # Required for OIDC login
      contents: read

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set dynamic tags
      - name: Set Docker image tags
        id: tags
        run: |
          # Short SHA
          COMMIT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          # Branch name (replace / with -)
          BRANCH_NAME=$(echo "${GITHUB_REF_NAME}" | tr / -)
          echo "IMAGE_TAG=${COMMIT_SHA}" >> $GITHUB_ENV
          echo "IMAGE_TAG_FULL=${BRANCH_NAME}-${COMMIT_SHA}" >> $GITHUB_ENV
          echo "Image tags: $IMAGE_TAG, $IMAGE_TAG_FULL"

      # 3️⃣ Login to Azure via OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: OIDC
          environment: azurecloud

      # 4️⃣ Login to Azure Container Registry
      - name: Azure Container Registry Login
        run: az acr login --name ${{ env.ACR_NAME }}

      # 5️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
                       -t ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_FULL }} .

      # 6️⃣ Push Docker image
      - name: Push Docker image to ACR
        run: |
          docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_FULL }}

      # 7️⃣ Optional: List images in ACR
      - name: List images in ACR
        run: az acr repository list --name ${{ env.ACR_NAME }} --output table
